### PR TITLE
Introduce a proper make setup.

### PR DESCRIPTION
**Pull request by rasben**
- Remove docker-sync
- Introduce **optional** docker NFS setup for mac
- Fix issues with non existent .make files from ding2
- Actually apply patches from ding2 (Was this never done in the past??)
- Fix an issue with gulp (Again - how did this work before??)
- Introduce an easy way to setup the development environment - all explained in the readme, but long story short:

**(Please, reviewer: actually git clone this repo so you start from scratch!)**

```sh
$ git clone https://github.com/reload/ding-docker.git
$ cd ding-docker
```
If you use **Mac**, and have [**NFS setup** on your machine (HIGHLY RECOMMENDED, btw!)](https://reload.atlassian.net/wiki/spaces/RW/pages/153288705/Docker+for+Mac#DockerforMac-5.NFS) please run:
```sh
$ cp docker-compose.mac-nfs.yml docker-compose.override.yml
```

Otherwise/afterwards, continue:
```sh
$ make
$ make drush-make
$ make reset
```

To setup the correct git remotes, do this:
(Maybe this should be a `make` command also?)
```sh
$ cd web/profiles/ding2
$ git remote add origin git@github.com:reload/ding2.git
$ git remote add upstream git@github.com:ding2/ding2.git
$ git fetch origin
$ git fetch upstream
$ git checkout master
```

You should now have a site on
[https://ding2.docker](https://ding2.docker)

### CODE REVIEW

**Comment by xendk** [comment]
If you run make with  --working-copy, there's no need to set up origin. Adding the reload remote in the makefile could be handy though.

I've removed this repo from Circle. It wasn't set up, so it just fails anyway.

BTW, [task](https://taskfile.dev/#/) is the new make. :-)

**Comment by kasperg** [comment]
@rasben I just tried this out. After having to install SVN to make `make drush-make` work I end up with the following error when running `make reset`:

```
08:48 $ make reset
rm -f .last-pull-*
docker-compose pull
Pulling gulp      ... done
Pulling memcached ... done
Pulling mailhog   ... done
Pulling db        ... done
Pulling fpm       ... done
Pulling web       ... done
touch .last-pull-20200514
./scripts/docker/docker-reset.sh
Password:

Successfully started nginx proxy
Successfully started dnsmasq
Requesting sudo to write to /etc/resolver/docker
Successfully configured local resolver
*** Removing existing containers
No stopped containers
Removing network ding-docker_default
WARNING: Network ding-docker_default not found.
Removing volume ding-docker_cache
WARNING: Volume ding-docker_cache not found.
Removing volume ding-docker_db-data
WARNING: Volume ding-docker_db-data not found.
Removing volume ding-docker_projectroot
WARNING: Volume ding-docker_projectroot not found.
*** Starting new containers
Creating network "ding-docker_default" with the default driver
Creating volume "ding-docker_cache" with default driver
Creating volume "ding-docker_db-data" with default driver
Creating volume "ding-docker_projectroot" with local driver
Creating ding-docker_mailhog_1 ...
Creating ding-docker_gulp_1      ... error
Creating ding-docker_memcached_1 ...
Creating ding-docker_mailhog_1   ... done

Creating ding-docker_memcached_1 ... done
Creating ding-docker_db_1        ... done
Creating ding-docker_fpm_1       ... error

ERROR: for ding-docker_fpm_1  Cannot create container for service fpm: failed to mount local volume: mount :/tmp/ding-docker:/var/lib/docker/volumes/ding-docker_projectroot/_data, data: addr=192.168.65.2,nolock,hard,nointr,nfsvers=3: permission denied

ERROR: for gulp  Cannot start service gulp: error while mounting volume '/var/lib/docker/volumes/ding-docker_projectroot/_data': failed to mount local volume: mount :/tmp/ding-docker:/var/lib/docker/volumes/ding-docker_projectroot/_data, data: addr=192.168.65.2,nolock,hard,nointr,nfsvers=3: permission denied

ERROR: for fpm  Cannot create container for service fpm: failed to mount local volume: mount :/tmp/ding-docker:/var/lib/docker/volumes/ding-docker_projectroot/_data, data: addr=192.168.65.2,nolock,hard,nointr,nfsvers=3: permission denied
ERROR: Encountered errors while bringing up the project.
make: *** [_reset-container-state] Error 1
```

**Comment by rasben** [comment]
@kasperg Do you use NFS? and which MacOS are you using?

**Comment by kasperg** [comment]
I am running Catalina 10.15.4 and as far as I can tell I have NFS running:

bash 2020-05-14 11-33-56

**Comment by rasben** [comment]
@xendk 

> "Adding the reload remote in the makefile could be handy though."

I've added it now :) 5b94ae6

> "I've removed this repo from Circle. It wasn't set up, so it just fails anyway."

Thanks!

> "BTW, task is the new make. :-)"

I know, I know - I just dont have time right now to experiment with new tools.
Once this gets merged in, you're more than welcome to port it over though! 

I do think that its always easier to port over something exisiting :)

**Comment by rasben** [comment]
@kasperg When you have time, could i get you to go quickly through the NFS steps on confluence?
https://reload.atlassian.net/wiki/spaces/RW/pages/153288705/Docker+for+Mac#DockerforMac-5.NFS

But really - i know you're busy at the moment, so no stress!
This setup works for me, and it doesnt block my work at all for it to wait until it gets merged into master :)

**Comment by rasben** [comment]
oh - and did you remember to do `cp docker-compose.mac-nfs.yml docker-compose.override.yml` ?

**Comment by kasperg** [comment]
I think I completed all the step and have been using NFS on other projects.

Let's take a look at it together once we get the chance.

**Comment by CarstenHoyer** [comment]
I had a few hickups on my way, but they did not seem to be related to project - I needed SVN and my Ruby died when checking for Dory (but again, I think it was my setup).

My 2.1 Gb database dump was not ready even after 1200 seconds, so it might be a good idea to bump the timeout on the "wait-for-it" operation.

**Comment by CarstenHoyer** [comment]
My issue was that I was using a site dump, and I had kinda forgotten how that worked. So in order to make this setup work with a dump, you need to put the database in /docker/db, copy over /sites from your dump and (since I figured this out after building the site) move your dumps site folder to default and copy the settings.php from the old sites default directory.

I spoke with @kasperg  about this. We think it is unrelated to this PR, and I should make an updated README _after_ this PR has been merged.

But the thing about timeout on the database should be part of this PR I think.

**Pull request merged**
